---
- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: 'result.rc == 0'
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install requirements (RedHat)
  yum: name={{item}}
  with_items: [openvpn, openssl, zip]

- name: Install dependencies (RedHat)
  yum: name=python-passlib
  when: openvpn_use_pam_users|length

- name: Install easy-rsa package
  yum: name=easy-rsa
  when: openvpn_use_system_easyrsa

- name: Install LDAP dependencies (Debian)
  yum: name=openvpn-auth-ldap
  when: openvpn_use_ldap

- name: Install bridge dependencies (RedHat)
  yum: name=bridge-utils
  when: openvpn_bridge
